version: '2'
services:
  concourse-db:
    image: postgres:9.5
    volumes: ['./database:/database']
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    restart: on-failure:10

  concourse-web:
    image: concourse/concourse
    command: web
    ports: ['8080:8080']
    volumes: ['./web-keys:/concourse-keys']
    depends_on: [keys, concourse-db]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: admin
      CONCOURSE_BASIC_AUTH_PASSWORD: admin
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    restart: on-failure:10

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    depends_on: [keys]
    volumes: ['./worker-keys:/concourse-keys']
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
    restart: on-failure:10

  keys:
    build: .
    volumes:
      - ./web-keys:/keys/web
      - ./worker-keys:/keys/worker
