service: hello-api-gateway

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  index:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{param+}

custom:
  webpack:
    packager: yarn
