service: serverless-large-spike

plugins:
  - serverless-webpack
  # - serverless-parcel

provider:
  name: aws
  runtime: nodejs10.x

# you can add packaging information here
package:
   individually: true
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  svc1:
    handler: svc1.handler
    events:
       - http:
           path: svc1
           method: get
  svc2:
    handler: svc2.handler
    events:
       - http:
           path: svc2
           method: get

  svc3:
    handler: svc3.handler
    events:
       - http:
           path: svc3
           method: get

  svc4:
    handler: svc4.handler
    events:
       - http:
           path: svc4
           method: get

custom:
  webpack:
    packager: 'yarn'
    includeModules: true
    packageModules: true
  parcel:
    options:
      target: node
      cache: true
    entries:
      - file: dummy.ts
        target: node
        outFile: dist/dummy.js
